"""
Reports Module — Generate and export Excel and PDF reports.
"""
import streamlit as st
import pandas as pd
import io
import os
from datetime import datetime
from authentication import check_auth, require_role
from database import get_connection
from utils.visualization import kpi_card
from utils.auth import log_activity
from config import REPORTS_DIR

# ── Auth ──
user = check_auth()
if not user:
    st.switch_page("app.py")
require_role("Reports")

st.markdown("# 📑 Reports")
st.markdown("Generate and export professional banking reports")
st.markdown("---")

REPORT_TYPES = {
    "Customer Report": {"table": "customers", "description": "Comprehensive customer data report"},
    "Loan Report": {"table": "loans", "description": "Loan portfolio analysis report"},
    "Transaction Report": {"table": "transactions", "description": "Transaction activity report"},
    "Fraud Report": {"table": "transactions", "filter": "is_fraud = 1", "description": "Fraudulent transaction report"},
    "Credit Risk Report": {"table": "customers", "description": "Customer credit risk assessment report"},
    "Customer Segmentation Report": {"table": "customers", "description": "Customer segmentation analysis"},
    "Churn Report": {"table": "customers", "description": "Customer churn analysis report"},
    "Executive Dashboard Summary": {"table": None, "description": "High-level executive summary"},
}

# ── Report Selection ──
selected_report = st.selectbox("Select Report Type", list(REPORT_TYPES.keys()))
report_config = REPORT_TYPES[selected_report]

st.info(f"📋 **{selected_report}**: {report_config['description']}")

# ── Configuration ──
c1, c2 = st.columns(2)
with c1:
    export_format = st.selectbox("Export Format", ["Excel (.xlsx)", "PDF (.pdf)"])
with c2:
    max_rows = st.number_input("Max Rows", value=1000, min_value=100, max_value=10000, step=100)

# ── Generate Report ──
st.markdown("---")

if st.button("📊 Generate Report", type="primary", use_container_width=True):
    with st.spinner("Generating report..."):
        conn = get_connection()

        # Fetch data
        if selected_report == "Executive Dashboard Summary":
            # Build executive summary
            customers = pd.read_sql("SELECT COUNT(*) as c FROM customers", conn).iloc[0]["c"]
            accounts = pd.read_sql("SELECT COUNT(*) as c FROM accounts", conn).iloc[0]["c"]
            loans = pd.read_sql("SELECT COUNT(*) as c FROM loans", conn).iloc[0]["c"]
            txns = pd.read_sql("SELECT COUNT(*) as c FROM transactions", conn).iloc[0]["c"]
            total_deposits = pd.read_sql("SELECT COALESCE(SUM(amount), 0) as s FROM transactions WHERE type='Deposit'", conn).iloc[0]["s"]
            total_loans_amt = pd.read_sql("SELECT COALESCE(SUM(loan_amount), 0) as s FROM loans", conn).iloc[0]["s"]
            avg_balance = pd.read_sql("SELECT COALESCE(AVG(balance), 0) as a FROM customers", conn).iloc[0]["a"]
            fraud_count = pd.read_sql("SELECT COUNT(*) as c FROM transactions WHERE is_fraud = 1", conn).iloc[0]["c"]

            summary_data = pd.DataFrame([
                {"Metric": "Total Customers", "Value": f"{customers:,}"},
                {"Metric": "Total Accounts", "Value": f"{accounts:,}"},
                {"Metric": "Total Loans", "Value": f"{loans:,}"},
                {"Metric": "Total Transactions", "Value": f"{txns:,}"},
                {"Metric": "Total Deposits", "Value": f"${total_deposits:,.2f}"},
                {"Metric": "Total Loan Amount", "Value": f"${total_loans_amt:,.2f}"},
                {"Metric": "Average Balance", "Value": f"${avg_balance:,.2f}"},
                {"Metric": "Fraud Alerts", "Value": f"{fraud_count:,}"},
            ])
            df = summary_data
        elif "filter" in report_config:
            df = pd.read_sql(f"SELECT * FROM {report_config['table']} WHERE {report_config['filter']} LIMIT {max_rows}", conn)
        else:
            df = pd.read_sql(f"SELECT * FROM {report_config['table']} LIMIT {max_rows}", conn)

        conn.close()

        # ── Preview ──
        st.markdown("### 📋 Report Preview")
        st.markdown(f"**Records:** {len(df)} | **Columns:** {len(df.columns)}")
        st.dataframe(df.head(50), use_container_width=True)

        # ── Export ──
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        filename = f"{selected_report.replace(' ', '_')}_{timestamp}"

        if "Excel" in export_format:
            buffer = io.BytesIO()
            with pd.ExcelWriter(buffer, engine='openpyxl') as writer:
                df.to_excel(writer, index=False, sheet_name="Report")

                # Add metadata sheet
                meta = pd.DataFrame([
                    {"Field": "Report Type", "Value": selected_report},
                    {"Field": "Generated By", "Value": user["full_name"]},
                    {"Field": "Generated At", "Value": datetime.now().strftime("%Y-%m-%d %H:%M:%S")},
                    {"Field": "Total Records", "Value": str(len(df))},
                ])
                meta.to_excel(writer, index=False, sheet_name="Metadata")

            buffer.seek(0)
            st.download_button(
                "📥 Download Excel Report",
                buffer,
                f"{filename}.xlsx",
                "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
                use_container_width=True
            )

        else:  # PDF
            try:
                from reportlab.lib.pagesizes import letter, landscape
                from reportlab.lib import colors
                from reportlab.platypus import SimpleDocTemplate, Table, TableStyle, Paragraph, Spacer
                from reportlab.lib.styles import getSampleStyleSheet
                from reportlab.lib.units import inch

                buffer = io.BytesIO()
                doc = SimpleDocTemplate(buffer, pagesize=landscape(letter))
                styles = getSampleStyleSheet()
                elements = []

                # Title
                elements.append(Paragraph(f"<b>{selected_report}</b>", styles["Title"]))
                elements.append(Paragraph(f"Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')} | By: {user['full_name']}", styles["Normal"]))
                elements.append(Spacer(1, 0.25 * inch))

                # Table data (limit columns for PDF readability)
                display_cols = df.columns[:8].tolist()
                table_data = [display_cols]
                for _, row in df.head(100).iterrows():
                    table_data.append([str(row[col])[:30] for col in display_cols])

                if table_data:
                    t = Table(table_data)
                    t.setStyle(TableStyle([
                        ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#1B2A4A')),
                        ('TEXTCOLOR', (0, 0), (-1, 0), colors.HexColor('#D4AF37')),
                        ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
                        ('FONTSIZE', (0, 0), (-1, 0), 8),
                        ('FONTSIZE', (0, 1), (-1, -1), 7),
                        ('BOTTOMPADDING', (0, 0), (-1, 0), 8),
                        ('GRID', (0, 0), (-1, -1), 0.5, colors.grey),
                        ('ROWBACKGROUNDS', (0, 1), (-1, -1), [colors.white, colors.HexColor('#F8F9FA')]),
                    ]))
                    elements.append(t)

                doc.build(elements)
                buffer.seek(0)

                st.download_button(
                    "📥 Download PDF Report",
                    buffer,
                    f"{filename}.pdf",
                    "application/pdf",
                    use_container_width=True
                )
            except ImportError:
                st.error("❌ ReportLab not installed. Please install it: `pip install reportlab`")

        # Log activity
        log_activity(user["user_id"], user["username"], "REPORT_GENERATED", f"Generated {selected_report} ({export_format})")
        st.success(f"✅ Report generated successfully!")
